### ISSUE TITLE
optimize parameters for large genome

### ISSUE THREAD

**Issue by rwhetten** [bcgsc/goldrush#109]
I'm interested in using Goldrush to assemble ONT reads of a large, highly repetitive diploid plant genome (haploid size~22 Gb). The long reads have been error-corrected using FMLRC2 based on an FM-index of Illumina short-read data from the same individual. Are the default parameters for Goldrush likely to be optimal for a genome of this size and complexity? If not, can you suggest changes that might improve them? I have a job running now that completed the silver path and golden path steps, and has been aligning the long reads to the golden path for weeks. The job is using 60 threads with minimap2, and is slowly making progress, so it is not hung, but it is much slower than other jobs aligning long reads to draft assemblies of the same genome. I'm wondering if this is a consequence of artifacts in the golden path due to inappropriate parameter settings.

**Comment by jwcodee** [comment]
@rwhetten 
Thank you for your interest in using GoldRush for your projects.
The GoldRush parameters are not optimal for a genome of your size and complexity. We are working on a solution for genome of that size and complexity. The following suggestions are experimental:
* k = 24
* w = 18
* s = 101101111011110111101101

Because the size of certain plant genomes are so large, k and w sizes need to be adjusted to accommodate for the possible number of k-mers (and incorrect k-mers). Do note, that due to the increase in k and w, GoldRush will now need upwards of ~800GB to run for plant genomes of that size, but since your reads are corrected, the RAM usage should be lower than estimated.

**Comment by rwhetten** [comment]
OK, thanks. I have access to a compute node with 1 Tb RAM, so I'll do a test on that node.

**Comment by rwhetten** [comment]
The job used up to 1.2 Tb RAM, which is not a problem, but the resulting assembly is about 2x the expected size (46 Gb instead of 23), and consists of 1.9 million scaffolds with N50 of around 30 kb, which is similar to the N50 of the long read data used. Are there other parameter adjustments that would help to increase contiguity? A haplotype-separated diploid assembly would be great if that is possible, but at this point it is not useful.

**Comment by jwcodee** [comment]
Unfortunately, GoldRush with genome of that size and complexity is very experimental. The results you show is in line with we have in-house and it is unlikely that the generated assembly is haplotype-separated. Unfortunately I don't think simple parameter changes will be enough to assemble genome of that size and complexity. This will be one of the tasks we will actively work on.
