### ISSUE TITLE
Goldrush for PacBio or ONT + PacBio

### ISSUE THREAD

**Issue by 000generic** [bcgsc/goldrush#116]
Hi! 

I was wondering if Goldrush has been tested / is used / is recommended for PacBio data - or ONT + PacBio data? If so, are there any specific recommendations? I have data sets for two species with around human-sized genomes. One with 40x ONT + 7x PacBio and another with 10x ONT + 60x PacBio - all data generated around 2020.

Thank you :)
Eric

**Comment by jwcodee** [comment]
Thanks for your interest and sorry for the delayed response.

GoldRush has been tested on just PacBio Hi-Fi data. GoldRush assembles PacBio Hi-Fi data well in our experiments (high base quality and single digit MB NGA50) but the genome assemblies do not reach the level of contiguity of ONT genome assemblies due to the lower read length, which affects the scaffolding algorithm used.

I'm not sure if you have Hi-Fi or CLR but If you were to use GoldRush on PacBio Hi-Fi data, you will have to change the `m` parameter to the library sized used in generation of the PacBio Hi-Fi data. 

Right now, GoldRush does not support hybrid data out of the box. It is possible to manually generate the golden path with PacBio data and scaffold with ONT though we have not explored how much coverage is needed for optimal scaffolding. We are looking to add that option in a future update.


60X and 40X should be sufficient coverage to run the GoldRush pipeline.

**Comment by 000generic** [comment]
Thank you for all the details! Very helpful
