### ISSUE TITLE
Error when running goldrush_test_demo

### ISSUE THREAD

**Issue by haraldgrove** [bcgsc/goldrush#123]
Hi

I've just started testing your program and ran into an issue when trying the demonstration.

I installed the software using conda as described and downloaded the github repository to find the demo-program.

When I ran the program (using slurm) I got the following error:

```
<...>
echo "Done GoldRush-Path! Golden path can be found in: goldrush_test_golden_path.fa"
Done GoldRush-Path! Golden path can be found in: goldrush_test_golden_path.fa
rm -f goldrush_test_silver_path_*.fq
Clean Done
goldrush-ulimit goldrush-edit --minimap2 -t4 -m/dev/shm goldrush_test_golden_path.fa test_reads.fq goldrush_test_golden_path.goldrush-edit-polished.fa
Running with 1030656 max processes: goldrush-edit --minimap2 -t4 -m/dev/shm goldrush_test_golden_path.fa test_reads.fq goldrush_test_golden_path.goldrush-edit-polished.fa
  File "/mnt/users/harag/.conda/envs/goldrush/bin/goldrush-edit", line 308
    while record := reader.read():
                  ^
SyntaxError: invalid syntax
make: *** [/mnt/users/harag/.conda/envs/goldrush/bin/goldrush.make:233: goldrush_test_golden_path.goldrush-edit-polished.fa] Error 1
```
The program had generated one file: `goldrush_test_golden_path.fa`. It's not quite the same name as in the README description, but is this the expected final output?

Can you tell what went wrong here?

-Harald

**Comment by lcoombe** [comment]
Hi @haraldgrove,

Did you install goldrush into a fresh conda environment, or into a pre-existing one? What version of python is installed? It looks like it's error-ing out at that walrus operator, which is only available in python 3.8+.

If your python version looks sufficient, it would help to see a `conda list` of the packages installed in your conda environment.

Due to the error, GoldRush did not generate the final expected output - the `goldrush_test_golden_path.fa` file is the output of the GoldPath stage, and is the 'golden path' - See our [README](https://github.com/bcgsc/goldrush#general-steps-in-the-algorithm), [wiki](https://github.com/bcgsc/goldrush/wiki) or [paper](https://www.nature.com/articles/s41467-023-38716-x) for more details about the steps of GoldRush.

Thank you for your interest in GoldRush!
Lauren

**Comment by haraldgrove** [comment]
Sorry, I think the problem was on my end. I got a tip about checking which `python3` file that was first in the path and it was not the one in the GoldRush environment (unlike `python`). After fixing that problem, the program ran to the end.

-Harald

**Comment by lcoombe** [comment]
Hi Harald - excellent, I'm glad to hear that you solved the issue!
